# Static CRT so tagfix.exe runs without the VC++ redistributable.
# Everything the exe needs beyond Windows itself ships inside the exe;
# the only external requirement is the WebView2 runtime, which is part
# of Windows 11.
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
